# Generated by Django 4.2.11 on 2024-07-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_seed_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
