# Generated by Django 4.2.11 on 2024-07-05 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0003_alter_movie_runtime_alter_movie_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Terrible"),
                            (2, "Dislike"),
                            (3, "Decent"),
                            (4, "Good"),
                            (5, "Awesome"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("review_date", models.DateField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewers",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
